import { useState } from 'react';
import { toast } from 'sonner';
import Icon from '../components/Icon.jsx';
import { date, money } from '../utils/format.js';
import { downloadCsv, printReceipt } from '../utils/export.js';
export default function Activity({ transactions }) {
  const [filter, setFilter] = useState('all');
  const rows = transactions.filter(t => filter === 'all' || t.type === filter);
  const sales = transactions.filter(t => t.type === 'sale');
  const payments = transactions.filter(t => t.type === 'payment');
  function exportRows() { downloadCsv('creditstock-recent-transactions.csv', ['Date', 'Type', 'Product', 'Customer', 'Quantity', 'Total', 'Paid', 'Amount', 'Note'], transactions.map(t => [date(t.createdAt), t.type, t.product?.name, t.customer?.name, t.quantity, t.total, t.paid, t.amount, t.note])); }
  return <>
    <section className="page-intro"><div><span className="eyebrow">YOUR RECORDS</span><h2>Everything has a history.</h2><p>Follow your latest 100 sales, payments, and inventory changes.</p></div><button className="btn soft" onClick={exportRows}><Icon name="download" size={17}/> Export CSV</button></section>
    <section className="mini-metrics"><div><span className="mini-icon violet"><Icon name="receipt"/></span><div><small>Recent sales</small><strong>{sales.length}</strong></div></div><div><span className="mini-icon orange"><Icon name="wallet"/></span><div><small>Recent payments</small><strong>{payments.length}</strong></div></div><div><span className="mini-icon blue"><Icon name="activity"/></span><div><small>Total records shown</small><strong>{transactions.length}</strong></div></div></section>
    <section className="panel table-card"><div className="table-card-head"><div><h3>Transaction timeline</h3><p>The most recent activity appears first.</p></div></div><div className="filter-tabs">{[['all', 'All activity'], ['sale', 'Sales'], ['payment', 'Payments'], ['stock', 'Stock changes']].map(([key, label]) => <button key={key} className={filter === key ? 'selected' : ''} onClick={() => setFilter(key)}>{label}</button>)}</div><div className="table-wrap"><table><thead><tr><th>TRANSACTION</th><th>DETAILS</th><th>DATE</th><th>AMOUNT</th><th>ACTION</th></tr></thead><tbody>{rows.map(t => <tr key={t._id}><td><div className="product-cell"><span className={'transaction-avatar ' + t.type}><Icon name={t.type === 'sale' ? 'receipt' : t.type === 'payment' ? 'wallet' : 'inventory'} size={18}/></span><div><strong>{t.type === 'sale' ? 'Product sale' : t.type === 'payment' ? 'Credit payment' : 'Stock movement'}</strong><small>{t.type === 'sale' ? t.product?.name || 'Product' : t.type === 'payment' ? t.customer?.name || 'Customer' : t.product?.name || 'Product'}</small></div></div></td><td>{t.type === 'sale' ? t.quantity + ' units' + (t.customer ? ' · ' + t.customer.name : ' · walk-in') : t.type === 'payment' ? 'Balance reduced' : Math.abs(t.amount) + ' units ' + (t.amount > 0 ? 'added' : 'removed') + (t.note ? ' · ' + t.note : '')}</td><td>{date(t.createdAt)}</td><td><strong className={t.type === 'payment' ? 'received' : ''}>{t.type === 'sale' ? money(t.total) : t.type === 'payment' ? money(t.amount) : (t.amount > 0 ? '+' : '') + t.amount + ' units'}</strong></td><td>{t.type === 'sale' ? <button className="table-link" onClick={() => { if (!printReceipt(t)) toast.error('Allow popups to print the receipt'); }}>Print receipt</button> : '—'}</td></tr>)}</tbody></table></div>{rows.length === 0 && <div className="table-empty"><span className="empty-illustration"><Icon name="activity" size={26}/></span><strong>{transactions.length === 0 ? 'Your activity starts with a sale' : 'No transactions in this category'}</strong><p>Sales, payments, and stock movements appear here as you record them.</p></div>}<div className="table-footer">Showing {rows.length} recent records · Receipts are available for sales</div></section>
  </>;
}
