import { useState } from 'react';
import { toast } from 'sonner';
import Icon from '../components/Icon.jsx';
import { money } from '../utils/format.js';
import { downloadCsv, openCreditReminder } from '../utils/export.js';
export default function Customers({ customers, open }) {
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('all');
  const owing = customers.filter(c => c.balance > 0);
  const rows = customers.filter(c => (c.name + c.phone).toLowerCase().includes(search.toLowerCase()) && (filter === 'all' || (filter === 'due' ? c.balance > 0 : c.balance <= 0)));
  const total = customers.reduce((n, c) => n + c.balance, 0);
  function exportRows() { downloadCsv('creditstock-customers.csv', ['Name', 'Phone', 'Outstanding balance'], customers.map(c => [c.name, c.phone, c.balance])); }
  return <>
    <section className="page-intro"><div><span className="eyebrow">CUSTOMER LEDGER</span><h2>Credit that stays clear.</h2><p>Give every customer a profile and every payment a place to land.</p></div><button className="btn primary" onClick={() => open({ type: 'customer' })}><Icon name="plus" size={17}/> Add customer</button></section>
    <section className="mini-metrics"><div><span className="mini-icon orange"><Icon name="wallet"/></span><div><small>Outstanding credit</small><strong>{money(total)}</strong></div></div><div><span className="mini-icon violet"><Icon name="customers"/></span><div><small>Customers</small><strong>{customers.length}</strong></div></div><div><span className="mini-icon blue"><Icon name="activity"/></span><div><small>Balances to collect</small><strong>{owing.length}</strong></div></div></section>
    <section className="panel table-card"><div className="table-card-head"><div><h3>Customer accounts</h3><p>Open a ledger or log a payment anytime.</p></div><div className="table-tools"><label className="search-box"><Icon name="search" size={18}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search customers..." aria-label="Search customers"/></label><button className="btn soft" onClick={exportRows}><Icon name="download" size={16}/> Export</button></div></div><div className="filter-tabs">{[['all', 'All customers'], ['due', 'Payment due'], ['clear', 'Clear balance']].map(([key, label]) => <button key={key} className={filter === key ? 'selected' : ''} onClick={() => setFilter(key)}>{label}{key === 'due' && owing.length > 0 && <span>{owing.length}</span>}</button>)}</div><div className="table-wrap"><table><thead><tr><th>CUSTOMER</th><th>CONTACT</th><th>OUTSTANDING</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>{rows.map(c => <tr key={c._id}><td><div className="product-cell"><span className="customer-avatar">{c.name.slice(0, 2).toUpperCase()}</span><div><strong>{c.name}</strong><small>Customer account</small></div></div></td><td>{c.phone || 'No phone added'}</td><td><strong className={c.balance > 0 ? 'due' : ''}>{money(c.balance)}</strong></td><td><span className={'status-badge ' + (c.balance > 0 ? 'low' : 'ok')}><i/>{c.balance > 0 ? 'Payment due' : 'Clear'}</span></td><td><div className="row-actions"><button onClick={() => open({ type: 'ledger', item: c })}>View ledger</button><button disabled={c.balance <= 0} onClick={() => open({ type: 'payment', item: c })}>Payment</button><button disabled={c.balance <= 0 || !c.phone} onClick={() => { if (!openCreditReminder(c)) toast.error('Add a valid phone number to send a reminder'); }}>Remind</button><button onClick={() => open({ type: 'customer', item: c })}>Edit</button></div></td></tr>)}</tbody></table></div>{rows.length === 0 && <div className="table-empty"><span className="empty-illustration"><Icon name="customers" size={26}/></span><strong>{customers.length === 0 ? 'Your first customer goes here' : 'No customers match your filters'}</strong><p>{customers.length === 0 ? 'Add a customer before recording a credit sale.' : 'Try another search or filter.'}</p>{customers.length === 0 && <button className="btn primary" onClick={() => open({ type: 'customer' })}>Add customer</button>}</div>}<div className="table-footer">Showing {rows.length} of {customers.length} customers</div></section>
  </>;
}
