import { useState } from 'react';
import Icon from '../components/Icon.jsx';
import { money } from '../utils/format.js';
import { downloadCsv } from '../utils/export.js';
export default function Inventory({ products, open }) {
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('all');
  const low = products.filter(p => p.stock <= p.reorderLevel);
  const value = products.reduce((n, p) => n + p.stock * p.costPrice, 0);
  const rows = products.filter(p => (p.name + p.sku + p.category).toLowerCase().includes(search.toLowerCase()) && (filter === 'all' || (filter === 'low' ? p.stock <= p.reorderLevel : p.stock > p.reorderLevel)));
  function exportRows() { downloadCsv('creditstock-products.csv', ['Name', 'SKU', 'Category', 'Selling price', 'Cost price', 'Stock', 'Reorder level'], rows.map(p => [p.name, p.sku, p.category, p.sellingPrice, p.costPrice, p.stock, p.reorderLevel])); }
  return <>
    <section className="page-intro"><div><span className="eyebrow">YOUR CATALOG</span><h2>Know what’s on every shelf.</h2><p>Keep products organized and catch low stock before it slows you down.</p></div><button className="btn primary" onClick={() => open({ type: 'product' })}><Icon name="plus" size={17}/> Add product</button></section>
    <section className="mini-metrics"><div><span className="mini-icon violet"><Icon name="inventory"/></span><div><small>Total products</small><strong>{products.length}</strong></div></div><div><span className="mini-icon orange"><Icon name="warning"/></span><div><small>Need restocking</small><strong>{low.length}</strong></div></div><div><span className="mini-icon blue"><Icon name="layers"/></span><div><small>Inventory cost value</small><strong>{money(value)}</strong></div></div></section>
    <section className="panel table-card"><div className="table-card-head"><div><h3>All products</h3><p>Manage pricing and stock movement from one list.</p></div><div className="table-tools"><label className="search-box"><Icon name="search" size={18}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search name, SKU..." aria-label="Search products"/></label><button className="btn soft" onClick={exportRows}><Icon name="download" size={16}/> Export</button></div></div><div className="filter-tabs">{[['all', 'All products'], ['low', 'Low stock'], ['healthy', 'In stock']].map(([key, label]) => <button key={key} className={filter === key ? 'selected' : ''} onClick={() => setFilter(key)}>{label}{key === 'low' && low.length > 0 && <span>{low.length}</span>}</button>)}</div><div className="table-wrap"><table><thead><tr><th>PRODUCT</th><th>CATEGORY</th><th>PRICE</th><th>STOCK LEVEL</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>{rows.map(p => <tr key={p._id}><td><div className="product-cell"><span className="product-avatar">{p.name.slice(0, 2).toUpperCase()}</span><div><strong>{p.name}</strong><small>SKU: {p.sku}</small></div></div></td><td>{p.category}</td><td><strong>{money(p.sellingPrice)}</strong><small>Cost {money(p.costPrice)}</small></td><td><div className="stock-level"><strong>{p.stock} units</strong><span className="stock-track"><span className={p.stock <= p.reorderLevel ? 'low' : ''} style={{ width: Math.min(100, p.stock / Math.max(1, p.reorderLevel * 2) * 100) + '%' }}/></span></div></td><td><span className={'status-badge ' + (p.stock === 0 ? 'out' : p.stock <= p.reorderLevel ? 'low' : 'ok')}><i/>{p.stock === 0 ? 'Out of stock' : p.stock <= p.reorderLevel ? 'Low stock' : 'In stock'}</span></td><td><div className="row-actions"><button onClick={() => open({ type: 'stock', item: p })}>Adjust stock</button><button onClick={() => open({ type: 'product', item: p })}>Edit</button></div></td></tr>)}</tbody></table></div>{rows.length === 0 && <div className="table-empty"><span className="empty-illustration"><Icon name="inventory" size={26}/></span><strong>{products.length === 0 ? 'Start with your first product' : 'No products match your filters'}</strong><p>{products.length === 0 ? 'Add your catalog to begin tracking sales and stock.' : 'Try another search or filter.'}</p>{products.length === 0 && <button className="btn primary" onClick={() => open({ type: 'product' })}>Add product</button>}</div>}<div className="table-footer">Showing {rows.length} of {products.length} products</div></section>
  </>;
}
