import Icon from '../components/Icon.jsx';
import SalesChart from '../components/SalesChart.jsx';
import ShopCharts from '../components/ShopCharts.jsx';
import { date, money } from '../utils/format.js';
const fallback = { todaySales: 0, todaySaleCount: 0, weeklySales: 0, outstandingCredit: 0, productCount: 0, customerCount: 0, inventoryValue: 0, lowStock: [], salesTrend: [] };
function Metric({ label, value, icon, tone, foot }) { return <div className="metric card"><span className={'metric-icon ' + tone}><Icon name={icon} size={21}/></span><span className="metric-label">{label}</span><strong>{value}</strong><small>{foot}</small></div>; }
export default function Overview({ data, setView, open }) {
  const d = data.dashboard || fallback;
  const owing = data.customers.filter(c => c.balance > 0).sort((a, b) => b.balance - a.balance);
  const recent = data.transactions.slice(0, 4);
  return <>
    <section className="hero"><div className="hero-copy"><span className="hero-kicker"><span className="live-dot"></span> YOUR SHOP AT A GLANCE</span><h2>Take control of your<br/><em>everyday business.</em></h2><p>Stock, sales, and customer credit—finally working together in one place.</p><div className="hero-actions"><button className="btn hero-primary" onClick={() => open({ type: 'sale' })}>Record a sale <Icon name="arrow" size={17}/></button><button className="btn hero-secondary" onClick={() => setView('inventory')}>Explore inventory</button></div></div><div className="hero-art"><div className="floating-card float-one"><span className="float-icon"><Icon name="inventory" size={21}/></span><div><small>PRODUCTS TRACKED</small><strong>{d.productCount}</strong></div></div><div className="hero-circle"><span>CS</span><small>CreditStock</small></div><div className="floating-card float-two"><span className="float-icon peach"><Icon name="wallet" size={21}/></span><div><small>CREDIT TO COLLECT</small><strong>{money(d.outstandingCredit)}</strong></div></div></div></section>
    <div className="section-heading"><div><span className="eyebrow">PERFORMANCE</span><h2>Today’s snapshot</h2></div><button className="text-link" onClick={() => setView('reports')}>View reports <Icon name="arrow" size={15}/></button></div>
    <section className="metrics">
      <Metric label="Sales today" value={money(d.todaySales)} foot={d.todaySaleCount + ' transactions today'} icon="trend" tone="violet" />
      <Metric label="Outstanding credit" value={money(d.outstandingCredit)} foot={owing.length + ' customers with balances'} icon="wallet" tone="orange" />
      <Metric label="Inventory value" value={money(d.inventoryValue)} foot="Based on product cost" icon="layers" tone="blue" />
      <Metric label="Low-stock items" value={d.lowStock.length} foot={d.lowStock.length ? 'Needs a restock soon' : 'Everything is stocked'} icon="warning" tone="pink" />
    </section>
    <section className="overview-grid"><div className="panel chart-panel"><div className="panel-head"><div><span className="eyebrow">SALES ACTIVITY</span><h3>Last 7 days</h3></div><span className="period-tag">This week</span></div><div className="chart-summary"><strong>{money(d.weeklySales)}</strong><span>Total sales this week</span></div><SalesChart trend={d.salesTrend}/></div><div className="panel action-panel"><div className="panel-head"><div><span className="eyebrow">QUICK ACTIONS</span><h3>What would you like to do?</h3></div></div><button className="quick-action" onClick={() => open({ type: 'sale' })}><span className="quick-icon violet"><Icon name="receipt"/></span><span><strong>Record a sale</strong><small>Keep your sales and stock in sync</small></span><Icon name="arrow" size={17}/></button><button className="quick-action" onClick={() => open({ type: 'product' })}><span className="quick-icon blue"><Icon name="inventory"/></span><span><strong>Add a product</strong><small>Build your inventory catalog</small></span><Icon name="arrow" size={17}/></button><button className="quick-action" onClick={() => open({ type: 'customer' })}><span className="quick-icon orange"><Icon name="customers"/></span><span><strong>Add a customer</strong><small>Track credit with confidence</small></span><Icon name="arrow" size={17}/></button></div></section>
    <ShopCharts products={data.products} customers={data.customers} />
    <section className="overview-grid lower"><div className="panel"><div className="panel-head"><div><span className="eyebrow">STOCK WATCH</span><h3>Products to restock</h3></div><button className="text-link" onClick={() => setView('inventory')}>See all <Icon name="arrow" size={14}/></button></div>{d.lowStock.length ? d.lowStock.slice(0, 4).map(p => <div className="watch-row" key={p._id}><span className="product-avatar">{p.name.slice(0, 2).toUpperCase()}</span><div><strong>{p.name}</strong><small>{p.sku} · reorder at {p.reorderLevel}</small></div><span className="stock-pill">{p.stock} left</span></div>) : <div className="panel-empty"><span className="empty-illustration"><Icon name="check" size={26}/></span><strong>All stocked up</strong><p>Products below their reorder level will appear here.</p></div>}</div><div className="panel"><div className="panel-head"><div><span className="eyebrow">LATEST UPDATES</span><h3>Recent activity</h3></div><button className="text-link" onClick={() => setView('activity')}>View all <Icon name="arrow" size={14}/></button></div>{recent.length ? recent.map(t => <div className="watch-row" key={t._id}><span className="activity-avatar"><Icon name={t.type === 'sale' ? 'trend' : t.type === 'payment' ? 'wallet' : 'inventory'} size={18}/></span><div><strong>{t.type === 'sale' ? 'Sale · ' + (t.product?.name || 'Product') : t.type === 'payment' ? 'Payment received' : 'Stock updated'}</strong><small>{date(t.createdAt)}</small></div><span className="recent-value">{t.type === 'sale' ? money(t.total) : t.type === 'payment' ? money(t.amount) : (t.amount > 0 ? '+' : '') + t.amount}</span></div>) : <div className="panel-empty"><span className="empty-illustration"><Icon name="activity" size={26}/></span><strong>Nothing here yet</strong><p>Your first transaction will show up here.</p></div>}</div></section>
  </>;
}
